#!/bin/bash

# aws s3 sync ./ s3://presentation.wolfymaster.com --exclude '.git/*' --exclude '.idea/*'

EXCLUDE_FILE="./excludes"

# Start building the command with the base
COMMAND="aws s3 sync ./ s3://presentation.wolfymaster.com"

# Read the file line by line
while IFS= read -r line; do
    # Skip empty lines
    if [ -n "$line" ]; then
        # Add the exclude option with the line quoted
        COMMAND="$COMMAND --exclude \"$line\""
    fi
done < "$EXCLUDE_FILE"

eval "$COMMAND"
